---
# tasks file for wildfly-svr

- name: Create wildfly installation folder
  become: true
  file:
    path: "{{ wildfly.home }}/wildfly-{{ wildfly.version }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Download and unpack wildfly
  become: true
  unarchive:
    remote_src: yes
    src: "http://download.jboss.org/wildfly/{{ wildfly_version }}/wildfly-{{ wildfly_version }}.tar.gz"
    dest: "{{ wildfly.home }}"
    owner: "root"
    group: "root"

- name: Create service base root folder
  become: true
  file:
    path: "{{ wildfly.base }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy standalone to service base folder
  become: true
  command: cp -pr "{{ wildfly.home }}/wildfly-{{ wildfly.version }}/standalone" "{{ wildfly.base }}/{{ wildfly.svc }}"

- name: Create service group
  become: true
  group:
    name: "{{ wildfly.svc }}"
    state: present

- name: Create service user
  become: true
  user:
    state: present
    name: "{{ wildfly.svc }}"
    group: "{{ wildfly.svc }}"
    home: "{{ wildfly.base }}/{{ wildfly.svc }}"
    shell: /sbin/nologin
    comment: "Service user for {{ wildfly.svc }} service."

- name: Set permissions on service base folder
  become: true
  file:
    dest: "{{ wildfly.base }}/{{ wildfly.svc }}"
    owner: "{{ wildfly.svc }}"
    group: "{{ wildfly.svc }}"
    recurse: true

- name: Create service run folder
  become: true
  file:
    path: "{{ wildfly.base }}/{{ wildfly.svc }}/run"
    state: directory
    owner: "{{ wildfly.svc }}"
    group: "{{ wildfly.svc }}"
    mode: 0755

- name: Create service environment file
  become: true
  template:
    src: service-env.j2
    dest: "/etc/default/{{ wildfly.svc }}"
    owner: root
    group: root
    mode: 0644

- name: Create service unit file
  become: true
  template:
    src: service-unit.j2
    dest: "/etc/systemd/system/{{ wildfly.svc }}.service"
    owner: root
    group: root
    mode: 0755

- name: Reload systemd daemons and start service
  become: true
  systemd:
    daemon_reload: true
    name: "{{ wildfly.svc }}"
    state: started
